### ISSUE TITLE
[Android] Sonic falls when trying to fly with Tails

### ISSUE THREAD

**Issue by slambo311** [Rubberduckycooly/RSDKv5-Decompilation#61] opened 2022-08-28 20:21 UTC
In Mania, every time I try to jump up and grab Tails' legs, he just falls. The animation for holding on still plays, though.

**Comment by santiagocezar** [comment] 2022-08-28 20:50
Sounds like a duplicate of #56?

**Comment by breakthetargets** [comment] 2022-08-28 22:57
Already fixed, also this isn't the correct repo to put it in.

**Closed** 2022-08-29 05:35 UTC
