### ISSUE TITLE
Black And White Cutscenes (Title screen cutscenes) (Android)

### ISSUE THREAD

**Issue by Swapnekokitten** [Rubberduckycooly/RSDKv5-Decompilation#29] opened 2022-08-21 16:41 UTC
Fix this bug

**Comment by breakthetargets** [comment] 2022-08-22 01:07
Not a bug, download the shaders and use them as a mod.

**Comment by Bright5park** [comment] 2022-08-22 22:05
I have the same issue on Linux, could you kindly point me to the shaders?

Also, slightly more clear instructions on how to load the shaders as "mods" would be good.
I try to do it according to how I understood the Readme in the shader source folder, but it doesn't seem to do anything if I have the source files in [Mania/RSDKv5 folder]/Mods/Data/Shaders/GL3, nor if the GL3 folder is sitting directly in the Mods folder.

**Comment by Swapnekokitten** [comment] 2022-08-23 10:21
> 

Hey man, I dont understand id like to see a tutorial on android. Please explain.

**Comment by MGRich** [comment] 2022-08-24 03:50
That means the backup shaders are activated. Current shaders don't work for the release APK, but Bright5park has the right idea, I will write a new setup/have it setup automatically for you(?)

Counting this as a duplicate of #8.

**Closed by MGRich** 2022-08-24 03:50 UTC

**Comment by Swapnekokitten** [comment] 2022-08-24 08:55
> That means the backup shaders are activated. Current shaders don't work for the release APK, but Bright5park has the right idea, I will write a new setup/have it setup automatically for you(?)
> 
> Counting this as a duplicate of #8.

It is not that kind of problem with the black screen the game works fine as intended, but when it reaches the Animation Cutscenes and I mean by this.
![5D6C9F3B-11BB-44FB-A473-5B7DF72572FC](https://user-images.githubusercontent.com/105176896/186375784-79a87e5f-7e7f-4216-af1c-ef0b48af5285.png)

**Comment by MGRich** [comment] 2022-08-24 18:10
Yeah, that means you don't have the required shaders. The current shaders only work if you build the current Android from source, so if you went and got the current shaders using the released APK, it would likely give you a black screen or use the backup shader again.

**Comment by yehyasabry** [comment] 2022-08-24 18:30
Can I ask you a question what the CPU that you use because in not work for me in mediatek

**Comment by MGRich** [comment] 2022-08-24 18:45
Mediatek I believe is fixed in master.

**Comment by Swapnekokitten** [comment] 2022-08-24 21:30
> 
I need a tutorial so I can actually know how to fix this problem.
