### ISSUE TITLE
black screen in sonic mania 

### ISSUE THREAD

**Issue by sUpersonic228** [Rubberduckycooly/RSDKv5-Decompilation#64] opened 2022-08-29 12:19 UTC
![1661775406959](https://user-images.githubusercontent.com/112397316/187199479-02ccf419-9f2c-41f7-9fa5-d07327b116a0.jpg)

**Comment by Deltara3** [comment] 2022-08-29 12:20
Known bug and this issue is a duplicate of another issue. Although may I have the full screenshot for logging purposes?

**Closed** 2022-08-29 12:22 UTC

**Comment by sUpersonic228** [comment] 2022-08-29 12:24
![Screenshot_20220829-192202](https://user-images.githubusercontent.com/112397316/187200318-6b1ac627-e906-4445-8d64-42ff1dbadc72.png)

**Comment by Deltara3** [comment] 2022-08-29 12:25
Thanks, I shall mark this as not working in my spreadsheet.

**Comment by sUpersonic228** [comment] 2022-08-29 12:29
Will this really be fixed?

**Comment by Deltara3** [comment] 2022-08-29 12:43
Eventually. This spreadsheet I am referring to is for basically purely documentational purposes as I help with this issue quite frequently. If you're in the Discord, await an announcement in decomp-announcements.

**Comment by sUpersonic228** [comment] 2022-08-29 12:49
where can i join the discord?
