### ISSUE TITLE
(android)Black screen 

### ISSUE THREAD

**Issue by MounirXD7** [Rubberduckycooly/RSDKv5-Decompilation#35] opened 2022-08-22 11:44 UTC
I'm wondering if this problem is going to get fixed in the next update or in other future updates

**Comment by MounirXD7** [comment] 2022-08-22 14:05
HELL YEAH
But i need to compile some files or i can download the apk and install it?

**Comment by Kiyathepro** [comment] 2022-08-22 14:56
are you talking about how to install?
or something else

**Comment by LittlePlanetCD** [comment] 2022-08-23 02:36
the black screen bug is a known issue for Android, and is being worked on as best as one of the devs can do.

you only need to compile the APK itself if you want to have Sonic Mania's Plus DLC.

**Comment by MGRich** [comment] 2022-08-24 03:51
Duplicate of #8.

**Closed by MGRich** 2022-08-24 03:51 UTC
