### ISSUE TITLE
Game crashes after exiting a stage and backing out of the save menu

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#106] opened 2022-08-18 00:28 UTC
this is an android bug, but it also affects the switch port.

basically entering a stage via the save menu, pausing and exiting to the save menu, then backing out of that menu causes a crash.

**Comment by MGRich** [comment] 2022-09-27 20:01
This has been debugged further and has been revealed to be n RSDKv5 issue. The original issue from August is a defect of the UltrawideMania mod, but in new commits, the Switch crashes after **4a4dc1c8ceb73daa4407e3a8f4df2f8848809ad7 of RSDKv5 specifically.** Considering the scale of this commit's rewrites and neither me nor RDC being the one to work on this, I will be assigning this issue to @Clownacy. Please let Cosmic know if you need assistance.

**Comment by Clownacy** [comment] 2022-09-30 13:43
I cannot recreate this crash. Aside from a bunch of reformatting, 4a4dc1c8ceb73daa4407e3a8f4df2f8848809ad7 only changes a few things, as explained in [this comment](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/pull/73#issuecomment-1243521619). If each of those changes are applied one at a time to a pre-commit version of `Storage.cpp`, that might narrow down the crash on your end.

**Comment by MGRich** [comment] 2022-09-30 16:17
It was singled out to the commit listed. Reverting only said commit does not crash, as even the rest of your commits in the same PR work fine.

**Comment by Clownacy** [comment] 2022-09-30 17:52
Yes, but that commit is pretty big. If that commit is undone, and individual changes from it are reapplied (such as fixing the two bugs), the cause of the crash can be narrowed down further.

**Comment by LittlePlanetCD** [comment] 2022-10-03 20:33
> Yes, but that commit is pretty big. If that commit is undone, and individual changes from it are reapplied (such as fixing the two bugs), the cause of the crash can be narrowed down further.

this doesn't seem all that hard?

i assume you or i could test that, technically. maybe you could dm me on discord and tell me what exactly the fixes are to get rid of those two bugs? i might be able to take time to narrow it down

**Comment by LittlePlanetCD** [comment] 2022-10-03 20:36
> I cannot recreate this crash. Aside from a bunch of reformatting, [4a4dc1c](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/4a4dc1c8ceb73daa4407e3a8f4df2f8848809ad7) only changes a few things, as explained in [this comment](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/pull/73#issuecomment-1243521619). If each of those changes are applied one at a time to a pre-commit version of `Storage.cpp`, that might narrow down the crash on your end.

Although, this has gotten me curious.

What are you doing to test the crash? are you using real hardware or an emulator?

**Comment by Clownacy** [comment] 2022-10-04 01:55
I was testing in Yuzu.

The two bugs are...

`CopyStorage` fails to increment `entryCount`. Here's a fixed version:
```cpp
void RSDK::CopyStorage(int32 **src, int32 **dst)
{
    if (src) {
        int32 *dstPtr = *dst;
        *src          = *dst;

        DataStorageHeader *entry = (DataStorageHeader *)(dstPtr - 4);
        int32 setID              = entry->setID;

        if (dataStorage[setID].entryCount < STORAGE_ENTRY_COUNT) {
            dataStorage[setID].dataEntries[dataStorage[setID].entryCount]    = src;
            dataStorage[setID].storageEntries[dataStorage[setID].entryCount] = *src;

            ++dataStorage[setID].entryCount;

            if (dataStorage[setID].entryCount >= STORAGE_ENTRY_COUNT)
                CleanEmptyStorage((StorageDataSets)setID);
        }
    }
}
```

`AllocateStorage` always increments `entryCount`, even if allocation failed. Here's what the original pre-commit code looks like:
```cpp
                    DataStorageHeader *entry = (DataStorageHeader *)&storage->memoryTable[storage->usedStorage];

                    entry->active     = true;
                    entry->setID      = dataSet;
                    entry->dataOffset = storage->usedStorage + STORAGE_HEADER_SIZE;
                    entry->dataSize   = size;

                    storage->usedStorage += STORAGE_HEADER_SIZE;
                    *data = &storage->memoryTable[storage->usedStorage];
                    storage->usedStorage += size / sizeof(int32);

                    storage->dataEntries[storage->entryCount]    = data;
                    storage->storageEntries[storage->entryCount] = *data;
                }
            }
            else {
                DataStorageHeader *entry = (DataStorageHeader *)&storage->memoryTable[storage->usedStorage];

                entry->active     = true;
                entry->setID      = dataSet;
                entry->dataOffset = storage->usedStorage + STORAGE_HEADER_SIZE;
                entry->dataSize   = size;

                storage->usedStorage += STORAGE_HEADER_SIZE;
                *data = &storage->memoryTable[storage->usedStorage];
                storage->usedStorage += size / sizeof(int32);

                storage->dataEntries[storage->entryCount]    = data;
                storage->storageEntries[storage->entryCount] = *data;
            }

            ++storage->entryCount;
```
And here's a fixed version:
```cpp
                    DataStorageHeader *entry = (DataStorageHeader *)&storage->memoryTable[storage->usedStorage];

                    entry->active     = true;
                    entry->setID      = dataSet;
                    entry->dataOffset = storage->usedStorage + STORAGE_HEADER_SIZE;
                    entry->dataSize   = size;

                    storage->usedStorage += STORAGE_HEADER_SIZE;
                    *data = &storage->memoryTable[storage->usedStorage];
                    storage->usedStorage += size / sizeof(int32);

                    storage->dataEntries[storage->entryCount]    = data;
                    storage->storageEntries[storage->entryCount] = *data;
                    ++storage->entryCount;
                }
            }
            else {
                DataStorageHeader *entry = (DataStorageHeader *)&storage->memoryTable[storage->usedStorage];

                entry->active     = true;
                entry->setID      = dataSet;
                entry->dataOffset = storage->usedStorage + STORAGE_HEADER_SIZE;
                entry->dataSize   = size;

                storage->usedStorage += STORAGE_HEADER_SIZE;
                *data = &storage->memoryTable[storage->usedStorage];
                storage->usedStorage += size / sizeof(int32);

                storage->dataEntries[storage->entryCount]    = data;
                storage->storageEntries[storage->entryCount] = *data;
                ++storage->entryCount;
            }
```

**Comment by Rubberduckycooly** [comment] 2022-10-04 02:08
did not mean to close this lol

**Comment by LittlePlanetCD** [comment] 2022-10-04 02:21
https://github.com/Rubberduckycooly/RSDKv5-Decompilation/pull/111 did not fix the crash.

**Comment by LittlePlanetCD** [comment] 2022-10-04 02:23
> I was testing in Yuzu.

Yeah, yuzu skips over this crash. Ryujinx and Real hardware crash as they normally do.

**Closed** 2022-11-03 15:13 UTC
Labels: OS specific: switch, crash
