### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by KouTempest** [Rubberduckycooly/RSDKv5-Decompilation#33] opened 2022-08-21 21:30 UTC
please fix the issue where mediatek devices get a black screen with audio

**Comment by AshNoFake** [comment] 2022-08-22 06:47
RubberDuckCooly released a new uodate with bug fixes,even for Android,but,you have to compile it yourself

**Comment by yehyasabry** [comment] 2022-08-22 10:05
How can I compile it  can you help me please

**Comment by yehyasabry** [comment] 2022-08-22 10:14
I'm from Linux users I can compile apps in Linux only  put I not know  how to compile in android can you help me to compile it

**Comment by KouTempest** [comment] 2022-08-22 12:31
> RubberDuckCooly released a new uodate with bug fixes,also for Android,but,you have to compile it yourself

where did he post that

**Comment by yehyasabry** [comment] 2022-08-22 13:30
We made issus from 5days about the black screen and one from the developers of rsdk v5 last day tell me black screen have been fixed 
So I go to the file and he upgrade the file in GitHub  last day so we need to know now how to compile it  I can make that if I search and learn how to compile  in android so wait me I will know thank you for read

**Comment by KouTempest** [comment] 2022-08-22 13:34
> We made issus from 5days about the black screen and one from the developers of rsdk v5 last day tell me black screen have been fixed So I go to the file and he upgrade the file in GitHub last day so we need to know now how to compile it I can make that if I search and learn how to compile in android so wait me I will know thank you for read

thanks :D

**Comment by MounirXD7** [comment] 2022-08-22 13:52
So, there's a way to fix the black screen?(all mobile devices like armv7a devices?)

**Comment by yehyasabry** [comment] 2022-08-22 14:10
Yeah but I need help I  from Linux users so I can compile only in Linux but I now know how to compile app in android

**Comment by KouTempest** [comment] 2022-08-22 14:11
> Yeah but I need help I from Linux users so I can compile only in Linux but I now know how to compile app in android

you can go on the discord server for help

**Comment by MounirXD7** [comment] 2022-08-22 14:13
Hey bro if you compile the files (android)can you tell me? because i want to play it from the deep of my heart

**Comment by MounirXD7** [comment] 2022-08-22 14:14
> > Yeah but I need help I from Linux users so I can compile only in Linux but I now know how to compile app in android
> 
> you can go on the discord server for help

What server?

**Comment by yehyasabry** [comment] 2022-08-22 14:15
Ok man don't worry I will tell you

**Comment by MounirXD7** [comment] 2022-08-22 14:17
Thank you bro

**Comment by MounirXD7** [comment] 2022-08-22 14:22
Yes

**Comment by yehyasabry** [comment] 2022-08-22 14:23
وانا

**Comment by yehyasabry** [comment] 2022-08-22 14:27
Wait I can compile it with android studio so I need time

**Comment by KouTempest** [comment] 2022-08-22 14:31
> Wait I can compile it with android studio so I need time

alright thanks for the help though

**Comment by david331534** [comment] 2022-08-24 00:02
> Espera, puedo compilarlo con Android Studio, así que necesito tiempo.

Hey bro, have you finished compiling it yet? and if so can you post the apk please

**Comment by yehyasabry** [comment] 2022-08-24 01:55
I try and I have now old problems and new problems : the APK not installer and black screens me and deltra  make a test make shaders as mod so wait if it work we will tell you
And don't worry

**Comment by MGRich** [comment] 2022-08-24 03:50
Duplicate of #8.

**Closed by MGRich** 2022-08-24 03:50 UTC
