### ISSUE TITLE
[Android] Games hangs just before start of FBZ act 2

### ISSUE THREAD

**Issue by awe444** [Rubberduckycooly/RSDKv5-Decompilation#135] opened 2022-11-20 00:58 UTC
I'm on a Mali-GPU phone that only just started being able to run the game as of the black-screen fix. Compiled the APK myself including the DLC. The game is hanging for me after the FBZ act 1-->act 2 transition scene. The act 2 title card never appears and the character is stuck in the spot shown in screenshot below. The cloud layer continues its scrolling despite everything else hanging. I've disabled all mods and also found that the hang happens in encore mode.
![Screenshot_20221119-194749](https://user-images.githubusercontent.com/97898022/202877597-1189a89b-dde8-49fa-8519-b9012a074aec.png)

**Comment by MegAmi24** [comment] 2022-11-20 01:02
This is a bug with UltrawideMania that has already been fixed

**Comment by awe444** [comment] 2022-11-20 01:11
Thanks, is this version of UltraWideMania up to date (3 months ago last commit):
https://github.com/Rubberduckycooly/RSDKv5-Example-Mods/tree/master/UltrawideMania
That's where I sourced it when I setup my install yesterday.

**Comment by MGRich** [comment] 2022-11-20 02:27
Actually, I talked about in REMS how I had to add a fix to it, not that there *was* a fix implemented. So unfortunately, nothing to be done about this yet: technically works as intended. I'm closing as not planned, but I'll let you know here when I add a fix to UWM.

**Closed by MGRich** 2022-11-20 02:27 UTC
