### ISSUE TITLE
[GL3] Window turns black after confiming video settings in dev menu

### ISSUE THREAD

**Issue by Longestboi** [Rubberduckycooly/RSDKv5-Decompilation#52] opened 2022-08-27 00:59 UTC
When the video settings in the Dev Menu are confirmed, the window turns black.
It continues to stay black until the game is closed and then reopened.

![Screenshot from 2022-08-26 18-00-39](https://user-images.githubusercontent.com/21092212/187008155-aafcc9a0-af53-4a9d-bcc5-fbc7a786784e.png)
Exciting image, I know.

**Comment by MGRich** [comment] 2022-08-27 03:32
Duplicate of #17.

**Closed by MGRich** 2022-08-27 03:32 UTC
