### ISSUE TITLE
[Android] Metal Final Phase crashing

### ISSUE THREAD

**Issue by rajonpatNewAccount** [Rubberduckycooly/RSDKv5-Decompilation#57] opened 2022-08-27 12:33 UTC
When you go to metal's final phase it crashes FIX IT PLEAS

**Comment by Rubberduckycooly** [comment] 2022-08-29 05:38
Closing this since there's not enough information to be able to reproduce and it's in the wrong repo, if it still occurs make an issue in the mania repo

**Closed by Rubberduckycooly** 2022-08-29 05:38 UTC
