### ISSUE TITLE
Building Releases

### ISSUE THREAD

**Issue by Yaseen117** [Rubberduckycooly/RSDKv5-Decompilation#34] opened 2022-08-22 11:32 UTC
I dont have ANY idea on building those releases so please post them built then post their code at same time so people dont have to suffer i need the new build to see if it fixed the black screen error.

**Comment by MounirXD7** [comment] 2022-08-22 11:46
They released a new update?

**Comment by Yaseen117** [comment] 2022-08-22 12:26
> They released a new update?

Yes but you have to build it yourself

**Comment by MounirXD7** [comment] 2022-08-22 12:42
This is annoying but hey i appreciate their hard work

**Comment by MounirXD7** [comment] 2022-08-22 12:42
I wish for a tutorial about how i can build it

**Comment by Yaseen117** [comment] 2022-08-22 12:55
Yeah me too

**Comment by Deltara3** [comment] 2022-08-22 14:54
Instructions are on the README. Android's in particular is [here](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/blob/master/dependencies/android/README.md), but it's not too clear. I keep running into an issue where it fails to find `cpu.c` in the libtheora folder and I'm not entirely sure why. I feel like it must be generated by CMake but CMake fails to generate.

**Comment by Deltara3** [comment] 2022-08-22 15:00
Okay, I've found the solution to my issue. Android **does not** use the alpha build of libtheora like Windows does. Make sure to use libtheora release 1.1.1 and not libtheora alpha 1.2.0.

**Comment by KouTempest** [comment] 2022-08-22 15:08
> Okay, I've found the solution to my issue. Android **does not** use the alpha build of libtheora like Windows does. Make sure to use libtheora release 1.1.1 and not libtheora alpha 1.2.0.

soooo can you make a fixed apk for us?

**Comment by Deltara3** [comment] 2022-08-22 16:19
> > Okay, I've found the solution to my issue. Android **does not** use the alpha build of libtheora like Windows does. Make sure to use libtheora release 1.1.1 and not libtheora alpha 1.2.0.
> 
> soooo can you make a fixed apk for us?

Assuming the fixes are in master then I could, although I'm sure the team would prefer if someone compiles it themselves. Due to plus being enabled by default.

**Comment by Deltara3** [comment] 2022-08-22 16:40
Update to everyone, it does not appear to have been fixed yet.

**Comment by Deltara3** [comment] 2022-08-22 17:02
New update: I don't think the APK was really the issue. Add the shaders as a mod.

Create a new folder without spaces. Add this mod.ini to it. Name, author, description, and version don't have to match. TargetVersion must be 5 though.

`mod.ini`
```
Name=Shaders
Author=Null
Description=Not required
Version=v1.0
TargetVersion5
```

 After that, create a folder called Data, then inside the Data folder create a folder called Shaders. Copy the GL3 folder from this repository (located at [root]\RSDKv5\Shaders) into the Shaders directory of the mod folder. You should have the following tree.
 ```
 GL3Shaders (this will be your folder name)
 │   mod.ini
└───Data
    └───Shaders
        └───GL3
                Clean.fs
                CRT-Yee64.fs
                CRT-Yeetron.fs
                None.fs
                None.vs
                RGB-Image.fs
                YUV-420.fs
                YUV-422.fs
                YUV-444.fs
```
Copy this to sdcard\RSDK\V5\mods folder and edit the modconfig.ini there. Add `GL3Shaders=y` below `[Mods]`. Replace GL3Shaders with your folder name.

This may disable other mods so if it does just enable the others once more. Give this a shot. If this doesn't work then the APK was also part of the issue.

**Comment by KouTempest** [comment] 2022-08-22 20:20
> New update: ~I don't think the APK was really the issue.~ Add the shaders as a mod.
> 
> Create a new folder without spaces. Add this mod.ini to it. Name, author, description, and version don't have to match. TargetVersion must be 5 though.
> 
> `mod.ini`
> 
> ```
> Name=Shaders
> Author=Null
> Description=Not required
> Version=v1.0
> TargetVersion5
> ```
> 
> After that, create a folder called Data, then inside the Data folder create a folder called Shaders. Copy the GL3 folder from this repository (located at [root]\RSDKv5\Shaders) into the Shaders directory of the mod folder. You should have the following tree.
> 
> ```
> GL3Shaders (this will be your folder name)
> │   mod.ini
> └───Data
>    └───Shaders
>        └───GL3
>                Clean.fs
>                CRT-Yee64.fs
>                CRT-Yeetron.fs
>                None.fs
>                None.vs
>                RGB-Image.fs
>                YUV-420.fs
>                YUV-422.fs
>                YUV-444.fs
> ```
> 
> Copy this to sdcard\RSDK\V5\mods folder and edit the modconfig.ini there. Add `GL3Shaders=y` below `[Mods]`. Replace GL3Shaders with your folder name.
> 
> This may disable other mods so if it does just enable the others once more. ~Give this a shot. If this doesn't work then the APK was also part of the issue.~
> 
> ~If this doesn't work for you guys I'll look into compiling a build without Plus enabled.~
> 
> The APK still does have an issue, although these steps are necessary with the new build.

it didn't work :(

**Comment by Deltara3** [comment] 2022-08-22 21:34
> > New update: ~I don't think the APK was really the issue.~ Add the shaders as a mod.
> > Create a new folder without spaces. Add this mod.ini to it. Name, author, description, and version don't have to match. TargetVersion must be 5 though.
> > `mod.ini`
> > ```
> > Name=Shaders
> > Author=Null
> > Description=Not required
> > Version=v1.0
> > TargetVersion5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After that, create a folder called Data, then inside the Data folder create a folder called Shaders. Copy the GL3 folder from this repository (located at [root]\RSDKv5\Shaders) into the Shaders directory of the mod folder. You should have the following tree.
> > ```
> > GL3Shaders (this will be your folder name)
> > │   mod.ini
> > └───Data
> >    └───Shaders
> >        └───GL3
> >                Clean.fs
> >                CRT-Yee64.fs
> >                CRT-Yeetron.fs
> >                None.fs
> >                None.vs
> >                RGB-Image.fs
> >                YUV-420.fs
> >                YUV-422.fs
> >                YUV-444.fs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Copy this to sdcard\RSDK\V5\mods folder and edit the modconfig.ini there. Add `GL3Shaders=y` below `[Mods]`. Replace GL3Shaders with your folder name.
> > This may disable other mods so if it does just enable the others once more. ~Give this a shot. If this doesn't work then the APK was also part of the issue.~
> > ~If this doesn't work for you guys I'll look into compiling a build without Plus enabled.~
> > The APK still does have an issue, although these steps are necessary with the new build.
> 
> it didn't work :( but I appreciate your help, I wanted to make a build myself but I don't have a PC or anything like that

I would provide one but I can't for the life of me figure out how to build without Plus.

**Comment by KouTempest** [comment] 2022-08-22 21:45
> > > New update: ~I don't think the APK was really the issue.~ Add the shaders as a mod.
> > > Create a new folder without spaces. Add this mod.ini to it. Name, author, description, and version don't have to match. TargetVersion must be 5 though.
> > > `mod.ini`
> > > ```
> > > Name=Shaders
> > > Author=Null
> > > Description=Not required
> > > Version=v1.0
> > > TargetVersion5
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After that, create a folder called Data, then inside the Data folder create a folder called Shaders. Copy the GL3 folder from this repository (located at [root]\RSDKv5\Shaders) into the Shaders directory of the mod folder. You should have the following tree.
> > > ```
> > > GL3Shaders (this will be your folder name)
> > > │   mod.ini
> > > └───Data
> > >    └───Shaders
> > >        └───GL3
> > >                Clean.fs
> > >                CRT-Yee64.fs
> > >                CRT-Yeetron.fs
> > >                None.fs
> > >                None.vs
> > >                RGB-Image.fs
> > >                YUV-420.fs
> > >                YUV-422.fs
> > >                YUV-444.fs
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Copy this to sdcard\RSDK\V5\mods folder and edit the modconfig.ini there. Add `GL3Shaders=y` below `[Mods]`. Replace GL3Shaders with your folder name.
> > > This may disable other mods so if it does just enable the others once more. ~Give this a shot. If this doesn't work then the APK was also part of the issue.~
> > > ~If this doesn't work for you guys I'll look into compiling a build without Plus enabled.~
> > > The APK still does have an issue, although these steps are necessary with the new build.
> > 
> > 
> > it didn't work :( but I appreciate your help, I wanted to make a build myself but I don't have a PC or anything like that
> 
> I would provide one but I can't for the life of me figure out how to build without Plus.

you can try going to the discord server, they can help with that I think

**Comment by yehyasabry** [comment] 2022-08-23 05:26
Hey I follow your steps

**Comment by yehyasabry** [comment] 2022-08-23 05:56
Itest and same black screen

**Comment by Deltara3** [comment] 2022-08-23 12:19
> Itest and same black screen

Yeah I had tested myself with the old build and got the same results, compiling from source and doing that works wonders though. If I can figure out how to build without Plus I'll gladly supply an APK.

**Comment by yehyasabry** [comment] 2022-08-23 12:21
I can't use my computer to build sonic mania now I can build it with android studio but I can't because I'm not in home

**Comment by yehyasabry** [comment] 2022-08-23 12:23
What do you mean plus

**Comment by KouTempest** [comment] 2022-08-23 12:52
> What do you mean plus

plus is the dlc and sharing it is considered piracy

**Comment by Deltara3** [comment] 2022-08-23 17:49
I've got one compiled without Plus [here](https://drive.google.com/file/d/1ErIZ3xRv5QzgY5e6apJShCvRp79Pl1-r/view?usp=sharing). Install this instead and add the shaders as a mod and it should work. Make sure to uninstall any previous builds as this has a different signature.

**Comment by yehyasabry** [comment] 2022-08-23 18:34
Ok thanks

**Comment by yehyasabry** [comment] 2022-08-23 18:53
Now no thing happened only now we have black screen 😓 and no sound

**Comment by yehyasabry** [comment] 2022-08-23 19:58
Try it I think the problem In my phone

**Comment by david331534** [comment] 2022-08-23 23:47
hey bro I was reading your comments and something similar to the black screen happens to me

**Comment by david331534** [comment] 2022-08-23 23:50
what happens to me is that when opening rsdk itself the sonic mania screen looks quite small and the rest of the screen is already black

**Comment by david331534** [comment] 2022-08-23 23:52
> I've got one compiled without Plus [here](https://drive.google.com/file/d/1ErIZ3xRv5QzgY5e6apJShCvRp79Pl1-r/view?usp=sharing). Install this instead and add the shaders as a mod and it should work. Make sure to uninstall any previous builds as this has a different signature. Compiled from master.

hey bro i already installed your build but you say i need to use the shadders as mod?

**Comment by david331534** [comment] 2022-08-23 23:55
> I've got one compiled without Plus [here](https://drive.google.com/file/d/1ErIZ3xRv5QzgY5e6apJShCvRp79Pl1-r/view?usp=sharing). Install this instead and add the shaders as a mod and it should work. Make sure to uninstall any previous builds as this has a different signature. Compiled from master.

Thank you very much for your work, but could you tell me where I should get the shaders and can it be done from Android?

**Comment by david331534** [comment] 2022-08-23 23:57
> Tengo uno compilado sin Plus [aquí](https://drive.google.com/file/d/1ErIZ3xRv5QzgY5e6apJShCvRp79Pl1-r/view?usp=sharing) . Instale esto en su lugar y agregue los sombreadores como un mod y debería funcionar. Asegúrese de desinstalar cualquier compilación anterior, ya que tiene una firma diferente. Compilado de maestro.

I need to add the shaders but I can't find them, could you tell me where I can find it or send me a link? please I would appreciate it very much

**Comment by yehyasabry** [comment] 2022-08-24 01:48
Ok

**Comment by yehyasabry** [comment] 2022-08-24 01:50
> New update: ~I don't think the APK was really the issue.~ Add the shaders as a mod.
> 
> Create a new folder without spaces. Add this mod.ini to it. Name, author, description, and version don't have to match. TargetVersion must be 5 though.
> 
> `mod.ini`
> ```
> Name=Shaders
> Author=Null
> Description=Not required
> Version=v1.0
> TargetVersion5
> ```
> 
>  After that, create a folder called Data, then inside the Data folder create a folder called Shaders. Copy the GL3 folder from this repository (located at [root]\RSDKv5\Shaders) into the Shaders directory of the mod folder. You should have the following tree.
>  ```
>  GL3Shaders (this will be your folder name)
>  │   mod.ini
> └───Data
>     └───Shaders
>         └───GL3
>                 Clean.fs
>                 CRT-Yee64.fs
>                 CRT-Yeetron.fs
>                 None.fs
>                 None.vs
>                 RGB-Image.fs
>                 YUV-420.fs
>                 YUV-422.fs
>                 YUV-444.fs
> ```
> Copy this to sdcard\RSDK\V5\mods folder and edit the modconfig.ini there. Add `GL3Shaders=y` below `[Mods]`. Replace GL3Shaders with your folder name.
> 
> This may disable other mods so if it does just enable the others once more. ~Give this a shot. If this doesn't work then the APK was also part of the issue.~
> 
> ~If this doesn't work for you guys I'll look into compiling a build without Plus enabled.~
> 
> The APK still does have an issue, although these steps are necessary with the new build.

**Comment by yehyasabry** [comment] 2022-08-24 01:50
> I've got one compiled without Plus [here](https://drive.google.com/file/d/1ErIZ3xRv5QzgY5e6apJShCvRp79Pl1-r/view?usp=sharing). Install this instead and add the shaders as a mod and it should work. Make sure to uninstall any previous builds as this has a different signature. Compiled from master.

And use this APK

**Comment by david331534** [comment] 2022-08-24 02:00
> si te sirve dinos

ok thank you very much that was what i needed to know

**Comment by david331534** [comment] 2022-08-24 02:01
> si te sirve dinos

I'll try to do it right now and if it works I'll let you know!

**Comment by yehyasabry** [comment] 2022-08-24 02:02
You are welcome  if you need help in any thing tell me

**Comment by david331534** [comment] 2022-08-24 02:04
> si te sirve dinos

By the way, do you speak Spanish or why did you tell me in Spanish?

**Comment by david331534** [comment] 2022-08-24 02:04
> You are welcome if you need help in any thing tell me

Gracias yo si hablo español

**Comment by yehyasabry** [comment] 2022-08-24 02:10
I can't use Spanish

**Comment by yehyasabry** [comment] 2022-08-24 02:11
But I think GitHub change lungague

**Comment by yehyasabry** [comment] 2022-08-24 02:12
I'm sorry for this

**Comment by david331534** [comment] 2022-08-24 02:13
> But I think GitHub change lungague

don't worry I also speak English only that I learned to speak Spanish

**Comment by david331534** [comment] 2022-08-24 03:16
> I'm sorry for this

Hello bro sorry for the delay I recently finished doing it

**Comment by david331534** [comment] 2022-08-24 03:18
> If it work for you tell us

I followed all the steps but unfortunately the screen is black and only with sound

**Comment by david331534** [comment] 2022-08-24 03:21
If you like, I can send you some screenshots so you can see if the folders are well created and in their correct place.

**Comment by david331534** [comment] 2022-08-24 03:22
If you like, I can send you some screenshots so you can see if the folders are well created and in their correct place.

**Comment by david331534** [comment] 2022-08-24 03:23
wait some minutes

**Comment by david331534** [comment] 2022-08-24 03:43
![2022_08_23_22 33 32](https://user-images.githubusercontent.com/111930784/186323961-ad1ddccb-a96f-4f45-9531-d5fed658bb3a.jpg)

**Comment by david331534** [comment] 2022-08-24 03:44
![2022_08_23_22 34 14](https://user-images.githubusercontent.com/111930784/186324066-b87bf79a-d607-4960-8e6b-05f3f3bb7afe.jpg)

**Comment by david331534** [comment] 2022-08-24 03:45
![2022_08_23_22 34 45](https://user-images.githubusercontent.com/111930784/186324124-d9c2280d-55d8-4e9d-83a1-c2ac809bf1b0.jpg)

**Comment by david331534** [comment] 2022-08-24 03:45
![Uploading 2022_08_23_22.37.01.jpg…]()

**Comment by david331534** [comment] 2022-08-24 03:47
![2022_08_23_22 37 01](https://user-images.githubusercontent.com/111930784/186324372-d740dc25-f633-4c6d-86d9-bed22ab16d1f.jpg)

**Comment by david331534** [comment] 2022-08-24 03:47
![2022_08_23_22 37 14](https://user-images.githubusercontent.com/111930784/186324417-3ceb47df-4cad-4f3a-973a-5d03c628a05a.jpg)

**Comment by david331534** [comment] 2022-08-24 03:48
![2022_08_23_22 38 12](https://user-images.githubusercontent.com/111930784/186324494-111b2cbe-7f58-485f-8a71-a5948fcce191.jpg)

**Comment by david331534** [comment] 2022-08-24 03:48
![2022_08_23_22 38 19](https://user-images.githubusercontent.com/111930784/186324543-ee279ad3-0399-4870-bdcf-d0ac51ee6cb0.jpg)

**Comment by david331534** [comment] 2022-08-24 03:48
![2022_08_23_22 39 28](https://user-images.githubusercontent.com/111930784/186324585-bfd36e31-755d-4a7f-8913-7dfcb3a31a7f.jpg)

**Comment by david331534** [comment] 2022-08-24 03:49
that is all

**Comment by david331534** [comment] 2022-08-24 03:50
any suggestions or questions?

**Comment by david331534** [comment] 2022-08-24 03:51
I wait your answer

**Comment by MGRich** [comment] 2022-08-24 03:55
Please do not spam the issue: it makes it really hard to read. From the looks of it, this just seems like an Android setup thread for.. whatever reason? Marking this as a duplicate of #8.

**Closed by MGRich** 2022-08-24 03:55 UTC

**Comment by david331534** [comment] 2022-08-24 04:01
> Please do not spam the issue: it makes it really hard to read. From the looks of it, this just seems like an Android setup thread for.. whatever reason? Marking this as a duplicate of #8.

oh really sorry i didn't know i was just sending a screenshot of what i did

**Comment by david331534** [comment] 2022-08-24 04:09
> Por favor, no envíe spam al problema: hace que sea muy difícil de leer. Por lo que parece, esto parece un hilo de configuración de Android por... ¿cualquiera que sea el motivo? Marcando esto como un duplicado de #8 .

I can delete spam if you want

**Comment by david331534** [comment] 2022-08-24 04:16
> I'm sorry for this

hey one of the contributors just closed this issue
