### ISSUE TITLE
Android screen is black

### ISSUE THREAD

**Issue by Cloud67TR** [Rubberduckycooly/RSDKv5-Decompilation#60] opened 2022-08-28 16:33 UTC
Evrything is working but screen is black 
my gpu is:PowerVR

**Comment by SamuelTheTechnoKid** [comment] 2022-08-28 18:28
> Evrything is working but screen is black my gpu is:PowerVR

This is a known issue. It's being worked on currently.

**Comment by MGRich** [comment] 2022-08-28 18:38
Duplicate of #8.

**Closed by MGRich** 2022-08-28 18:38 UTC
