### ISSUE TITLE
Blackscreen with music in Mediatek device

### ISSUE THREAD

**Issue by SuperSonic40** [Rubberduckycooly/RSDKv5-Decompilation#27] opened 2022-08-20 08:23 UTC

**Comment by LittlePlanetCD** [comment] 2022-08-20 09:10
if this device of yours is an android that doesn't have a snapdragon processor, then the decomp will not work for you.

wait for a fix.

**Comment by tedmakestuff** [comment] 2022-08-20 12:59
yeah, unfortunately the phone I tested it on, like yours doesn't work with the decomp, I tested it with Sonic Mania.
The game runs just fine, it just can't render, I was able to go through menus and play til I accidentally exited. Though it's not fun since you can't see anything, I kept losing my Rings.

**Comment by yehyasabry** [comment] 2022-08-21 06:10
I have mediatek CPU and I have now black screen😓

**Comment by MGRich** [comment] 2022-08-24 03:45
Duplicate of #8.

**Closed by MGRich** 2022-08-24 03:45 UTC

**Comment by SuperSonic40** [comment] 2022-10-11 08:08
Can u email me when there is a fix?

Il sab 20 ago 2022, 11:10 LittlePlanetCD ***@***.***> ha
scritto:
