### ISSUE TITLE
(RSDKv5u) SFX, Music, and some visual issues

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#21] opened 2022-08-18 08:50 UTC
~~- Some Sounds in Sonic CD aren't able to be played (e.g. Ring, Skidding, Signpost, pause menu open, score total) when using audio files from the mobile port (also affects steam sfx files too?) (this doesn't seem to affect the v4 side of v5u, it's only v3)~~

~~- Music fading doesnt work correctly (known in v4, not sure about v3 but it's likely it's there too). Example: hitting the signpost in GHZ1 makes the music fade, then come back, then it changes to the Act Clear theme.~~

~~- In Sonic CD, music doesn't completely fade out upon the time travel sequence commencing.~~

- visual and audio fade outs reset to zero for a brief second before the next scene/music track loads, seems to be in both v4 and v3?

edit by RMG:   where did cosmic list the pause menu thingy ??

**Comment by Rubberduckycooly** [comment] 2022-08-23 09:04
- music fade out issues fixed in a779bf3f1bcb04056c066a982c6f890531faf6ec
- most sfx issues fixed in e1ad62e129b9107491c4c45381969d8e5efb6f23
- pause menu open not fixed but not sure why that is, keeping issue open till I find out why

**Comment by Rubberduckycooly** [comment] 2022-09-06 04:08
> visual and audio fade outs reset to zero for a brief second before the next scene/music track loads
unable to reproduce this now, is this fixed?

**Comment by Rubberduckycooly** [comment] 2022-09-06 04:24
should now all be fixed as of 31c46bbe16267ac482a0917eddcc9309fe4def27

**Closed by Rubberduckycooly** 2022-09-06 04:24 UTC
Labels: version specific: rev0U/v3v4 legacy, audio
