### ISSUE TITLE
Black screen with audio (many people reported) 

### ISSUE THREAD

**Issue by Yaseen117** [Rubberduckycooly/RSDKv5-Decompilation#32] opened 2022-08-21 18:03 UTC
I have a huawei y9 2019 hisilicon kirin 710 the game runs with everything BUT without display i know its better to have a snapdragon but i want to play the game anywhere i have it on my pc so please post a fix or an update.

**Comment by tedmakestuff** [comment] 2022-08-21 19:14
I tried on a Redmi 9, same thing.

**Comment by MGRich** [comment] 2022-08-24 03:51
Duplicate of #8.

**Closed by MGRich** 2022-08-24 03:51 UTC
