### ISSUE TITLE
Sony DualSense crash

### ISSUE THREAD

**Issue by Hereward-GH** [Rubberduckycooly/RSDKv5-Decompilation#180] opened 2023-03-10 10:42 UTC
Everytime I connect my DualSense on pc, RSDKv5 crash.
I don't know why this happens.

**Comment by Hereward-GH** [comment] 2023-03-10 11:48
I've tried with Steam opened and closed... nothing.

**Comment by LittlePlanetCD** [comment] 2023-03-10 14:57
you need to use a renderer other than DX9 or DX11 that can support Playstation controllers.

that, or you use Steam Input with RSDKv5 in your library to make the game work.

**Comment by stxticOVFL** [comment] 2023-04-14 03:57
Duplicate of #15.

**Closed by stxticOVFL** 2023-04-14 03:57 UTC
