### ISSUE TITLE
(Android) Black screen with sounds

### ISSUE THREAD

**Issue by LucasMegaStriker** [Rubberduckycooly/RSDKv5-Decompilation#13] opened 2022-08-16 20:32 UTC
Trying to run on my Powkiddy X18S (Unisoc T618, Mali) and got black screen. Music seems to play just fine, and the controls too (built-in gamepad from the X18S). So, any fix for the black screen?

**Comment by LucasMegaStriker** [comment] 2022-08-16 21:13
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/9354716/log.txt)
The log file mentions missing GL files.

**Comment by LucasMegaStriker** [comment] 2022-08-16 21:14
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/9354722/log.txt)
The log file mentions missing GL files.

**Comment by SuperSonic40** [comment] 2022-08-20 09:10
Is cuz you have Mediatek processor or something else

**Comment by LittlePlanetCD** [comment] 2022-08-20 09:13
if this device of yours is an android that doesn't have a snapdragon processor, then the decomp will not work for you correctly.

This has been reported many times on different devices, so please wait for a fix when we can get to it.

**Comment by yehyasabry** [comment] 2022-08-21 06:12
Me have mediatek CPU and I have black screen

**Comment by MGRich** [comment] 2022-08-24 03:30
Duplicate of #8.

**Closed by MGRich** 2022-08-24 03:30 UTC
Labels: duplicate
